site_name: 書評まとめ
theme:
  name: material
  language: ja
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt
  favicon: favicon.png
  features:
    - tabs
nav:
  - このサイトについて: index.md
  - 技術書:
    - TOP: 010.tech/index.md
    - テスト駆動開発: 
      - TOP: 010.tech/010.test_driven_development/index.md
      - 第Ⅰ部 多国通貨: 
        - TOP: 010.tech/010.test_driven_development/010.the_money_example/index.md
        - 第1章 仮実装: 010.tech/010.test_driven_development/010.the_money_example/001.muiti_currency_money/index.md
        - 第2章 明白な実装: 010.tech/010.test_driven_development/010.the_money_example/002.degenerate_objects/index.md
        - 第3章 三角測量: 010.tech/010.test_driven_development/010.the_money_example/003.equality_for_all/index.md
        - 第4章 意図を語るテスト: 010.tech/010.test_driven_development/010.the_money_example/004.privacy/index.md
        - 第5章 原則をあえて破るとき: 010.tech/010.test_driven_development/010.the_money_example/005.franc-ly_speaking/index.md
        - 第6章 テスト不足に気づいたら: 010.tech/010.test_driven_development/010.the_money_example/006.equality_for_all_redux/index.md
        - 第7章 疑念をテストに翻訳する: 010.tech/010.test_driven_development/010.the_money_example/007.apples_and_oranges/index.md


  - ビジネス書: 
    - TOP: 020.business/index.md
  - 小説: 
    - TOP: 030.novel/index.md
    - 向日葵の咲かない夏: 030.novel/010.himawarinosakanainatsu/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      # pygments_style: monokai
      linenums: true
  - pymdownx.superfences
  - codehilite:
      noclasses: true
      pygments_style: colorful
      linenums: true
  - toc:
      permalink: true
  - attr_list
copyright: 'Copyright © 2023 - Book Review Ltd. Allrights Reserved.'