site_name: 書評まとめ
theme:
  name: material
  language: ja
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt
  favicon: favicon.png
  features:
    - tabs
nav:
  - このサイトについて: index.md
  - 技術書:
    - TOP: 010.tech/index.md
    - テスト駆動開発: 
      - TOP: 010.tech/010.test_driven_development/index.md
      - 第Ⅰ部 多国通貨: 
        - TOP: 010.tech/010.test_driven_development/010.the_money_example/index.md
        - 第1章 仮実装: 010.tech/010.test_driven_development/010.the_money_example/001.muiti_currency_money/index.md
        - 第2章 明白な実装: 010.tech/010.test_driven_development/010.the_money_example/002.degenerate_objects/index.md
        - 第3章 三角測量: 010.tech/010.test_driven_development/010.the_money_example/003.equality_for_all/index.md
        - 第4章 意図を語るテスト: 010.tech/010.test_driven_development/010.the_money_example/004.privacy/index.md
        - 第5章 原則をあえて破るとき: 010.tech/010.test_driven_development/010.the_money_example/005.franc-ly_speaking/index.md
        - 第6章 テスト不足に気づいたら: 010.tech/010.test_driven_development/010.the_money_example/006.equality_for_all_redux/index.md
        - 第7章 疑念をテストに翻訳する: 010.tech/010.test_driven_development/010.the_money_example/007.apples_and_oranges/index.md
        - 第8章 実装を隠す: 010.tech/010.test_driven_development/010.the_money_example/008.makin_objects/index.md
        - 第9章 歩幅の調整: 010.tech/010.test_driven_development/010.the_money_example/009.times_were_livin_in/index.md
        - 第10章 テストに聞いてみる: 010.tech/010.test_driven_development/010.the_money_example/010.interesting_times/index.md
        - 第11章 不要になったら消す: 010.tech/010.test_driven_development/010.the_money_example/011.the_roof_of_all_evil/index.md
        - 第12章 設計とメタファー: 010.tech/010.test_driven_development/010.the_money_example/012.addition_finally/index.md
        - 第13章 実装を導くテスト: 010.tech/010.test_driven_development/010.the_money_example/013.make_it/index.md
        - 第14章 学習用テストと回帰テスト: 010.tech/010.test_driven_development/010.the_money_example/014.change/index.md
        - 第15章 テスト任せとコンパイラ任せ: 010.tech/010.test_driven_development/010.the_money_example/015.mixed_currencies/index.md
        - 第16章 将来の読み手を考えたテスト: 010.tech/010.test_driven_development/010.the_money_example/016.abstraction_finally/index.md
        - 第17章 多国通貨の全体ふりかえり: 010.tech/010.test_driven_development/010.the_money_example/017.money_retrospective/index.md
      - 第Ⅱ部 xUnit: 
        - TOP: 010.tech/010.test_driven_development/020.the_xUnit_example/index.md
        - 第18章 xUnit へ向かう小さな一歩: 010.tech/010.test_driven_development/020.the_xUnit_example/018.first_steps_to_xunit/index.md
        - 第19章 前準備: 010.tech/010.test_driven_development/020.the_xUnit_example/019.set_the_table/index.md
        - 第20章 後片付け: 010.tech/010.test_driven_development/020.the_xUnit_example/020.cleaning_up_after/index.md
        - 第21章 数え上げ: 010.tech/010.test_driven_development/020.the_xUnit_example/021.counting/index.md
        - 第22章 失敗の扱い: 010.tech/010.test_driven_development/020.the_xUnit_example/022.dealing_with_failure/index.md
        - 第23章 スイートにまとめる: 010.tech/010.test_driven_development/020.the_xUnit_example/023.how_suite_it_is/index.md
        - 第24章 xUnitの全体ふりかえり: 010.tech/010.test_driven_development/020.the_xUnit_example/024.xunit_retrospective/index.md
      - 第Ⅲ部 テスト駆動開発のパターン: 
        - TOP: 010.tech/010.test_driven_development/030.patterns_for_test_driven_development/index.md
        - 第25章 テスト駆動開発のパターン: 010.tech/010.test_driven_development/030.patterns_for_test_driven_development/025.test_driven_development_patterns/index.md
        - 第26章 レッドバーのパターン: 010.tech/010.test_driven_development/030.patterns_for_test_driven_development/026.red_bar_patterns/index.md
        - 第27章 テスティングフレームワーク: 010.tech/010.test_driven_development/030.patterns_for_test_driven_development/027.testing_patterns/index.md
        - 第28章 グリーンバーのパターン: 010.tech/010.test_driven_development/030.patterns_for_test_driven_development/028.green_bar_patterns/index.md
        - 第29章 xUnitのパターン: 010.tech/010.test_driven_development/030.patterns_for_test_driven_development/029.xunit_patterns/index.md
        - 第30章 デザインパターン: 010.tech/010.test_driven_development/030.patterns_for_test_driven_development/030.design_patterns/index.md

  - ビジネス書: 
    - TOP: 020.business/index.md
  - 小説: 
    - TOP: 030.novel/index.md
    - 向日葵の咲かない夏: 030.novel/010.himawarinosakanainatsu/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      # pygments_style: monokai
      linenums: true
  - pymdownx.superfences
  - codehilite:
      noclasses: true
      pygments_style: colorful
      linenums: true
  - toc:
      permalink: true
  - attr_list
copyright: 'Copyright © 2023 - Book Review Ltd. Allrights Reserved.'